# Generated by Django 6.0.6 on 2026-06-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_application_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='established_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='number_of_students',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='university',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='university',
            name='image',
            field=models.ImageField(null=True, upload_to='universities/'),
        ),
    ]
